### ISSUE TITLE
Survey review of mobile p2p applications

### ISSUE THREAD

**Issue by jkosem** [ipfs/mobile-design-guidelines#3]
Survey review of mobile p2p applications - Identify and review features, capabilities, use-cases and authors of existing mobile p2p applications

> Key constraints are that the applications are mobile (native or web) and
> the network transport used is p2p.

### Survey list

- [x] [ManyVerse](https://www.manyver.se/) (iOS)
- [x] [ShareDrop](https://www.sharedrop.io/)
- [x] [Status](https://status.im/)
- [x] [FrostWire](https://www.frostwire.com/) (Android only)
- [x] [uTorrent Remote](https://www.utorrent.com/remote/) (Android)
- [x] [Haven](https://gethaven.app/) (iOS, runs on OpenBazaar)
- [x] Swarm/Fairdrop (mobile web)

### Backup to investigate if there is time / Likely out of scope
~~- [bitTorrent Mobile](https://www.bittorrent.com/bittorrent-android - not working)~~
- [Blockstack](https://blockstack.org/)

----

~~DTube? https://about.d.tube/~~
~~Scuttlebutt~~
~~Anything with DAT with mobile~~
~~[Solid](https://solidproject.org/)~~
~~- [Open Bazaar](https://openbazaar.org/features/) no mobile~~
~~[HighTail](https://www.hightail.com/) no mobile~~
~~[ZeroNet](https://zeronet.io/) desktop only~~
~~[Storj.io](https://storj.io/) desktop/server only~~
~~[Sia](https://sia.tech/) server only~~
~~[OpenGarden FireChat](https://opengarden.com/firechat) taken down~~
~~[MetaMask Mobile](https://medium.com/metamask/metamask-mobile-public-beta-a-feature-guide-and-walkthrough-9d01de7190ae) not available for release~~

**Comment by jkosem** [comment]
Not explicity qualified as p2p file sharing, but there are technically other "p2p" sharing applications and platforms for p2p money transfers and lending

**Comment by jkosem** [comment]
https://hackmd.io/@jkosem/Hy1F93mrU

**Comment by autonome** [comment]
Key constraints are that the applications are mobile (native or web) and
the network transport used is p2p.

**Comment by jkosem** [comment]
Scuttlebutt has no mobile client

**Comment by autonome** [comment]
There's an iOS one in development called Planetary. There's one called
Manyverse which is iOS or Android.

Also, Haven is an IPFS based e-commerce app. Worth looking at who 3Box
has on their website as examples of people who've built on top of
their service.

**Comment by jkosem** [comment]
DAT + mobile so far is looking like a bit of a dead end.

The nearest thing I could find is maybe [Mapeo](https://www.digital-democracy.org/mapeo/) by Digital Democracy.

[Ara](https://ara.one/) don't seem to have anything out or released, mobile or otherwise. [Archipel](https://arso.xyz/archipel) looks promising, but nothing mobile, but might be worth trying on desktop which seems to have the only way of doing anything with it. Nothing else linked from [DAT Project](https://dat.foundation/) or elsewhere has anything implemented.

**Comment by jkosem** [comment]
Likewise Solid doesn't seem to have anything implemented or user-usable to test either.

**Comment by jkosem** [comment]
Swarm, or rather (from what I can pick apart) an implementation of it [FairDrop](https://fairdrop.xyz/) looks like its a thing. I managed (FF current, iOS) to share a photo of a kitty.

![76415835-3d226880-639a-11ea-8e39-c02de525de63](https://user-images.githubusercontent.com/495102/78011628-1d9cb100-7344-11ea-80db-090aff1893fa.jpeg)

**Comment by mikeal** [comment]
Dat made a decision early on to do things that would only work in Node.js and not translate well to the browser. This has also left them without much of a mobile distribution channel.

In the last year or so I’ve seen that community seemingly move away from Dat and towards building on more of the libraries underneath like hypercore https://github.com/mafintosh/hypercore and the core contributors have been building a ton of stuff on contract through their company in Copenhagen https://github.com/hyperdivision some of which may be for mobile.

**Comment by jkosem** [comment]
> There's an iOS one in development called Planetary. There's one called Manyverse which is iOS or Android. Also, Haven is an IPFS based e-commerce app. Worth looking at who 3Box has on their website as examples of people who've built on top of their service.
> […](#)
> On Tue, Mar 10, 2020 at 3:36 PM Jim Kosem ***@***.***> wrote: Scuttlebutt has no mobile client — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Planetary iOS doesn't look to be anywhere although could be in beta, but can't find anything in the App Store or on their web page

However, Manyverse does seem to have an iOS client so will check that out.

**Comment by jkosem** [comment]
Seems like there is no stable uTorrent client for MacOS (Catalina) therefore can't create account which can only be done from desktop client

**Comment by jkosem** [comment]
> Seems like there is no stable uTorrent client for MacOS (Catalina) therefore can't create account which can only be done from desktop client

Can now run Android SDK emulator so might be able to test it (if time) if can run just from the Android app.
